export const routers = {
    login: "/login",
    signup: "/signup",
    forgot: "/forgot",
    profile: "/profile",
    changePassword: "/password/change",
    home: "/home",
    summary: "/summary",
    reviewanalytics: "/reviewanalytics",
    noticeanalytics: "/noticeanalytics",
    yourassets: "yourassets",
    viewdata: "/viewdata",
    reviewpannel: "/reviewpannel",
    noticepannel: "/noticepannel",
    submitcontent: "/submitcontent",
    textsubmit: "/textsubmit",    
    addgroup: "/addgroup",
    modifygroup: "/modifygroup",
    emailconfigration: "/emailconfigration",
    manual: "/manual",
}

export const buttonType = {
    edit: "edit",
    delete: "delete",
    process: "process",
    reject: "reject",
    assignStore: "assignStore",
    assignDelivery: "assignDelivery",
    detail: "detail",
    order: "order",
    secret: "secret",
    unlock: "unlock",
    icon: "icon",
    recharge: "recharge",
    cancelOrRefund: "cancel/refund",
    showOrHide: "show/hide",
    varient: "varient",
};